org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m
org.gradle.caching=false
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=false
# Built-in Kotlin (AGP) — migrated from legacy kotlin-android plugin
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
